CREATE TABLE IF NOT EXISTS `cn_v7_v8_industry_crosswalk` (
    `effective_date` DATE NOT NULL,
    `v8_local_industry_id` VARCHAR(32) NOT NULL,
    `v8_local_industry_name` VARCHAR(128) DEFAULT NULL,
    `v8_parent_id` VARCHAR(32) DEFAULT NULL,
    `v8_parent_name` VARCHAR(128) DEFAULT NULL,
    `v7_sw_l1_code` VARCHAR(32) DEFAULT NULL,
    `v7_sw_l1_name` VARCHAR(128) DEFAULT NULL,
    `v7_parent_code` VARCHAR(32) DEFAULT NULL,
    `v7_parent_name` VARCHAR(128) DEFAULT NULL,
    `src` VARCHAR(16) NOT NULL,
    `candidate_rank` INT NOT NULL,
    `best_match_flag` TINYINT(1) NOT NULL DEFAULT 0,
    `mapping_type` VARCHAR(32) NOT NULL,
    `manual_review_flag` TINYINT(1) NOT NULL DEFAULT 0,
    `shared_symbol_count` INT NOT NULL DEFAULT 0,
    `v8_symbol_count` INT NOT NULL DEFAULT 0,
    `v7_symbol_count` INT NOT NULL DEFAULT 0,
    `jaccard_score` DECIMAL(12, 6) NOT NULL DEFAULT 0.000000,
    `coverage_vs_v8` DECIMAL(12, 6) NOT NULL DEFAULT 0.000000,
    `coverage_vs_v7` DECIMAL(12, 6) NOT NULL DEFAULT 0.000000,
    `decision_reason` VARCHAR(255) DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`effective_date`, `v8_local_industry_id`, `src`, `candidate_rank`),
    KEY `idx_crosswalk_v8_src_best` (`v8_local_industry_id`, `src`, `best_match_flag`),
    KEY `idx_crosswalk_v7_src` (`v7_sw_l1_code`, `src`),
    KEY `idx_crosswalk_mapping_type` (`mapping_type`, `manual_review_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
