-- cn_market.cn_stock_fina_indicator
-- Historical quarterly financial-quality indicators.

CREATE TABLE IF NOT EXISTS `cn_stock_fina_indicator` (
    `symbol` varchar(10) NOT NULL,
    `end_date` date NOT NULL,
    `ann_date` date DEFAULT NULL,
    `report_type` varchar(32) DEFAULT NULL,
    `eps` decimal(18,6) DEFAULT NULL,
    `dt_eps` decimal(18,6) DEFAULT NULL,
    `bps` decimal(18,6) DEFAULT NULL,
    `ocfps` decimal(18,6) DEFAULT NULL,
    `roe` decimal(18,6) DEFAULT NULL,
    `roe_dt` decimal(18,6) DEFAULT NULL,
    `roa` decimal(18,6) DEFAULT NULL,
    `roic` decimal(18,6) DEFAULT NULL,
    `grossprofit_margin` decimal(18,6) DEFAULT NULL,
    `netprofit_margin` decimal(18,6) DEFAULT NULL,
    `profit_to_gr` decimal(18,6) DEFAULT NULL,
    `ocf_to_or` decimal(18,6) DEFAULT NULL,
    `debt_to_eqt` decimal(18,6) DEFAULT NULL,
    `debt_to_assets` decimal(18,6) DEFAULT NULL,
    `current_ratio` decimal(18,6) DEFAULT NULL,
    `quick_ratio` decimal(18,6) DEFAULT NULL,
    `ar_turn` decimal(18,6) DEFAULT NULL,
    `arturn_days` decimal(18,6) DEFAULT NULL,
    `inv_turn` decimal(18,6) DEFAULT NULL,
    `invturn_days` decimal(18,6) DEFAULT NULL,
    `or_yoy` double DEFAULT NULL,
    `netprofit_yoy` double DEFAULT NULL,
    `tr_yoy` double DEFAULT NULL,
    `q_sales_yoy` double DEFAULT NULL,
    `q_profit_yoy` double DEFAULT NULL,
    `q_ocf_yoy` double DEFAULT NULL,
    `source` varchar(64) DEFAULT NULL,
    `raw_payload` longtext DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`symbol`, `end_date`),
    KEY `idx_cn_stock_fina_indicator_ann_date` (`ann_date`),
    KEY `idx_cn_stock_fina_indicator_report_type` (`report_type`),
    KEY `idx_cn_stock_fina_indicator_roe` (`end_date`, `roe`),
    KEY `idx_cn_stock_fina_indicator_roa` (`end_date`, `roa`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
