-- cn_market.cn_stock_leader_sw_l1_latest_snap
-- Materialized latest snapshot for leader_score + SW L1 mapping + SW daily metrics.

CREATE TABLE IF NOT EXISTS `cn_stock_leader_sw_l1_latest_snap` (
    `trade_date` date NOT NULL,
    `symbol` varchar(10) NOT NULL,
    `stock_name` varchar(80) DEFAULT NULL,
    `stock_close` decimal(18,4) DEFAULT NULL,
    `bk_industry_id` varchar(32) DEFAULT NULL,
    `bk_industry_name` varchar(80) DEFAULT NULL,
    `market_cap` decimal(24,4) DEFAULT NULL,
    `total_mv` decimal(24,4) DEFAULT NULL,
    `circ_mv` decimal(24,4) DEFAULT NULL,
    `market_cap_rank` bigint DEFAULT NULL,
    `market_cap_percentile` double DEFAULT NULL,
    `leader_structural` int DEFAULT NULL,
    `leader_structural_ready` int DEFAULT NULL,
    `turnover_20d_avg` decimal(23,4) DEFAULT NULL,
    `turnover_20d_percentile` double DEFAULT NULL,
    `leader_liquidity` int DEFAULT NULL,
    `rs_20d_raw` double DEFAULT NULL,
    `rs_percentile` double DEFAULT NULL,
    `leader_trend` int DEFAULT NULL,
    `breakout_strength` varchar(16) DEFAULT NULL,
    `breakout_ready` int DEFAULT NULL,
    `leader_score` bigint DEFAULT NULL,
    `leader_bucket` varchar(16) DEFAULT NULL,
    `turnover_rank_in_industry` bigint DEFAULT NULL,
    `industry_members` bigint DEFAULT NULL,
    `sw_l1_id` varchar(16) DEFAULT NULL,
    `sw_l1_name` varchar(80) DEFAULT NULL,
    `sw_close` decimal(18,4) DEFAULT NULL,
    `sw_pct_change` decimal(18,6) DEFAULT NULL,
    `sw_pe` decimal(18,6) DEFAULT NULL,
    `sw_pb` decimal(18,6) DEFAULT NULL,
    `sw_float_mv` decimal(24,4) DEFAULT NULL,
    `built_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`trade_date`, `symbol`),
    KEY `idx_cn_stock_leader_sw_l1_latest_snap_symbol` (`symbol`),
    KEY `idx_cn_stock_leader_sw_l1_latest_snap_score` (`trade_date`, `leader_score`),
    KEY `idx_cn_stock_leader_sw_l1_latest_snap_sw` (`trade_date`, `sw_l1_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
