-- cn_market.cn_stock_balancesheet
-- Historical quarterly balance-sheet snapshots from Tushare balancesheet API.

CREATE TABLE IF NOT EXISTS `cn_stock_balancesheet` (
    `symbol` varchar(10) NOT NULL,
    `end_date` date NOT NULL,
    `ann_date` date DEFAULT NULL,
    `f_ann_date` date DEFAULT NULL,
    `report_type` varchar(32) DEFAULT NULL,
    `comp_type` varchar(8) DEFAULT NULL,
    `end_type` varchar(32) DEFAULT NULL,
    `money_cap` decimal(24,4) DEFAULT NULL,
    `trad_asset` decimal(24,4) DEFAULT NULL,
    `notes_receiv` decimal(24,4) DEFAULT NULL,
    `accounts_receiv` decimal(24,4) DEFAULT NULL,
    `oth_receiv` decimal(24,4) DEFAULT NULL,
    `prepayment` decimal(24,4) DEFAULT NULL,
    `inventories` decimal(24,4) DEFAULT NULL,
    `total_cur_assets` decimal(24,4) DEFAULT NULL,
    `fix_assets` decimal(24,4) DEFAULT NULL,
    `cip` decimal(24,4) DEFAULT NULL,
    `intan_assets` decimal(24,4) DEFAULT NULL,
    `goodwill` decimal(24,4) DEFAULT NULL,
    `total_nca` decimal(24,4) DEFAULT NULL,
    `total_assets` decimal(24,4) DEFAULT NULL,
    `st_borr` decimal(24,4) DEFAULT NULL,
    `notes_payable` decimal(24,4) DEFAULT NULL,
    `acct_payable` decimal(24,4) DEFAULT NULL,
    `adv_receipts` decimal(24,4) DEFAULT NULL,
    `total_cur_liab` decimal(24,4) DEFAULT NULL,
    `lt_borr` decimal(24,4) DEFAULT NULL,
    `bond_payable` decimal(24,4) DEFAULT NULL,
    `total_ncl` decimal(24,4) DEFAULT NULL,
    `total_liab` decimal(24,4) DEFAULT NULL,
    `total_hldr_eqy_exc_min_int` decimal(24,4) DEFAULT NULL,
    `total_hldr_eqy_inc_min_int` decimal(24,4) DEFAULT NULL,
    `source` varchar(64) DEFAULT NULL,
    `raw_payload` longtext DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`symbol`, `end_date`),
    KEY `idx_cn_stock_balancesheet_ann_date` (`ann_date`),
    KEY `idx_cn_stock_balancesheet_f_ann_date` (`f_ann_date`),
    KEY `idx_cn_stock_balancesheet_report_type` (`report_type`),
    KEY `idx_cn_stock_balancesheet_receiv` (`end_date`, `accounts_receiv`),
    KEY `idx_cn_stock_balancesheet_inventory` (`end_date`, `inventories`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
