CREATE TABLE IF NOT EXISTS `cn_inst_fund_hold_summary` (
  `INSTITUTION_TYPE` VARCHAR(20) NULL,
  `HOLD_DATE` VARCHAR(10) NULL,
  `STOCK_CODE` VARCHAR(20) NULL,
  `STOCK_NAME` VARCHAR(100) NULL,
  `FUND_HOUSE_NUM` BIGINT NULL,
  `TOTAL_SHARES` DECIMAL(24,2) NULL,
  `TOTAL_MARKET_VALUE` DECIMAL(20,2) NULL,
  `CHANGE_TYPE` VARCHAR(50) NULL,
  `CHANGE_SHARES` DECIMAL(24,2) NULL,
  `CHANGE_RATIO` DECIMAL(18,6) NULL,
  `CREATION_DATE` DATE NULL,
  KEY `idx_inst_fund_hold_type_date` (`INSTITUTION_TYPE`, `HOLD_DATE`),
  KEY `idx_inst_fund_hold_stock_date` (`STOCK_CODE`, `HOLD_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
