CREATE TABLE IF NOT EXISTS cn_event_earnings_express (
    symbol          VARCHAR(10)    NOT NULL,
    ann_date        DATE           NOT NULL,
    end_date        DATE           NOT NULL,
    revenue         DECIMAL(20,2),
    operate_profit  DECIMAL(20,2),
    total_profit    DECIMAL(20,2),
    n_income        DECIMAL(20,2),
    diluted_eps     DECIMAL(18,6),
    diluted_roe     DECIMAL(18,6),
    bps             DECIMAL(18,6),
    yoy_sales       DECIMAL(18,6),
    yoy_op          DECIMAL(18,6),
    yoy_tp          DECIMAL(18,6),
    yoy_dedu_np     DECIMAL(18,6),
    yoy_eps         DECIMAL(18,6),
    yoy_roe         DECIMAL(18,6),
    growth_assets   DECIMAL(18,6),
    source          VARCHAR(30),
    raw_payload     JSON,
    updated_at      DATETIME       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (symbol, ann_date, end_date),
    KEY idx_express_symbol (symbol),
    KEY idx_express_ann_date (ann_date),
    KEY idx_express_end_date (end_date)
);
