-- cn_market.cn_stock_fundamental_quality_snap
-- Materialized latest snapshot of monthly historical quality screen.

CREATE TABLE IF NOT EXISTS `cn_stock_fundamental_quality_snap` (
    `symbol` varchar(10) NOT NULL,
    `basic_trade_date` date NOT NULL,
    `month_key` char(6) DEFAULT NULL,
    `fina_end_date` date DEFAULT NULL,
    `ann_date` date DEFAULT NULL,
    `total_mv` decimal(24,4) DEFAULT NULL,
    `circ_mv` decimal(24,4) DEFAULT NULL,
    `pe` decimal(18,6) DEFAULT NULL,
    `pe_ttm` decimal(18,6) DEFAULT NULL,
    `pb` decimal(18,6) DEFAULT NULL,
    `ps` decimal(18,6) DEFAULT NULL,
    `ps_ttm` decimal(18,6) DEFAULT NULL,
    `eps` decimal(18,6) DEFAULT NULL,
    `revenue_growth_pct` decimal(18,6) DEFAULT NULL,
    `or_yoy` decimal(18,6) DEFAULT NULL,
    `tr_yoy` decimal(18,6) DEFAULT NULL,
    `q_sales_yoy` decimal(18,6) DEFAULT NULL,
    `debt_to_eqt` decimal(18,6) DEFAULT NULL,
    `grossprofit_margin` decimal(18,6) DEFAULT NULL,
    `netprofit_margin` decimal(18,6) DEFAULT NULL,
    `pass_eps_positive` tinyint DEFAULT NULL,
    `pass_revenue_growth_5` tinyint DEFAULT NULL,
    `pass_revenue_growth_10` tinyint DEFAULT NULL,
    `pass_debt_to_eqt_lt_2` tinyint DEFAULT NULL,
    `pass_gross_margin_positive` tinyint DEFAULT NULL,
    `quality_core_score` tinyint DEFAULT NULL,
    `quality_total_score` tinyint DEFAULT NULL,
    `quality_pass_core` tinyint DEFAULT NULL,
    `quality_pass_with_margin` tinyint DEFAULT NULL,
    `basic_source` varchar(64) DEFAULT NULL,
    `fina_source` varchar(64) DEFAULT NULL,
    `basic_raw_payload` longtext DEFAULT NULL,
    `fina_raw_payload` longtext DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`symbol`, `basic_trade_date`),
    KEY `idx_cn_stock_fundamental_quality_snap_dt` (`basic_trade_date`),
    KEY `idx_cn_stock_fundamental_quality_snap_month_key` (`month_key`),
    KEY `idx_cn_stock_fundamental_quality_snap_core` (`basic_trade_date`, `quality_pass_core`),
    KEY `idx_cn_stock_fundamental_quality_snap_score` (`basic_trade_date`, `quality_total_score`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
