-- cn_market.SP_BUILD_SECTOR_ROTATION_RANKED_LATEST

DROP PROCEDURE IF EXISTS `SP_BUILD_SECTOR_ROTATION_RANKED_LATEST`;

CREATE PROCEDURE `SP_BUILD_SECTOR_ROTATION_RANKED_LATEST`()
proc: BEGIN
    CALL SP_BUILD_SECTOR_ROTATION_RANKED_BY_DATE(NULL);
END proc;
