USE cn_market;

ALTER TABLE cn_stock_daily_price
    ADD COLUMN IF NOT EXISTS `OPEN` DOUBLE DEFAULT NULL AFTER `TRADE_DATE`,
    ADD COLUMN IF NOT EXISTS `CLOSE` DOUBLE DEFAULT NULL AFTER `OPEN`,
    ADD COLUMN IF NOT EXISTS `PRE_CLOSE` DOUBLE DEFAULT NULL AFTER `CLOSE`,
    ADD COLUMN IF NOT EXISTS `HIGH` DOUBLE DEFAULT NULL AFTER `PRE_CLOSE`,
    ADD COLUMN IF NOT EXISTS `LOW` DOUBLE DEFAULT NULL AFTER `HIGH`;
