-- Materialize cn_stock_leader_score_daily from cn_stock_leader_score_v2
-- This INSERT ON DUPLICATE KEY UPDATE refreshes the materialized table
-- with the latest leader score data computed by the v2 view.
-- The v2 view itself depends on v1, daily_basic, and daily_price_active_v.
--
-- Called by: StockBasicTask.run() after apply_view() refreshes v1 and v2.

INSERT INTO cn_stock_leader_score_daily (
    trade_date,
    industry_id,
    industry_name,
    symbol,
    name,
    close,
    amount,
    market_cap,
    total_mv,
    circ_mv,
    market_cap_rank,
    market_cap_percentile,
    leader_structural,
    leader_structural_ready,
    turnover_20d_avg,
    turnover_20d_percentile,
    leader_liquidity,
    rs_20d_raw,
    rs_percentile,
    leader_trend,
    breakout_strength,
    breakout_ready,
    leader_score,
    leader_bucket,
    turnover_rank_in_industry,
    industry_members,
    source
)
SELECT
    v2.trade_date,
    v2.industry_id,
    v2.industry_name,
    v2.symbol,
    v2.name,
    v2.close,
    v2.amount,
    v2.market_cap,
    v2.total_mv,
    v2.circ_mv,
    v2.market_cap_rank,
    v2.market_cap_percentile,
    v2.leader_structural,
    v2.leader_structural_ready,
    v2.turnover_20d_avg,
    v2.turnover_20d_percentile,
    v2.leader_liquidity,
    v2.rs_20d_raw,
    v2.rs_percentile,
    v2.leader_trend,
    v2.breakout_strength,
    v2.breakout_ready,
    v2.leader_score,
    v2.leader_bucket,
    v2.turnover_rank_in_industry,
    v2.industry_members,
    'materialized_from_v2'
FROM cn_stock_leader_score_v2 v2
WHERE v2.trade_date >= :start_date
  AND v2.trade_date <= :end_date
ON DUPLICATE KEY UPDATE
    industry_id            = VALUES(industry_id),
    industry_name          = VALUES(industry_name),
    name                   = VALUES(name),
    close                  = VALUES(close),
    amount                 = VALUES(amount),
    market_cap             = VALUES(market_cap),
    total_mv               = VALUES(total_mv),
    circ_mv                = VALUES(circ_mv),
    market_cap_rank        = VALUES(market_cap_rank),
    market_cap_percentile  = VALUES(market_cap_percentile),
    leader_structural      = VALUES(leader_structural),
    leader_structural_ready = VALUES(leader_structural_ready),
    turnover_20d_avg       = VALUES(turnover_20d_avg),
    turnover_20d_percentile = VALUES(turnover_20d_percentile),
    leader_liquidity       = VALUES(leader_liquidity),
    rs_20d_raw             = VALUES(rs_20d_raw),
    rs_percentile          = VALUES(rs_percentile),
    leader_trend           = VALUES(leader_trend),
    breakout_strength      = VALUES(breakout_strength),
    breakout_ready         = VALUES(breakout_ready),
    leader_score           = VALUES(leader_score),
    leader_bucket          = VALUES(leader_bucket),
    turnover_rank_in_industry = VALUES(turnover_rank_in_industry),
    industry_members       = VALUES(industry_members),
    source                 = VALUES(source),
    updated_at             = NOW();
