CREATE TABLE IF NOT EXISTS cn_event_fina_indicator (
    symbol              VARCHAR(10)    NOT NULL,
    ann_date            DATE           NOT NULL,
    end_date            DATE           NOT NULL,
    report_type         VARCHAR(20),
    eps                 DECIMAL(18,6),
    dt_eps              DECIMAL(18,6),
    roe                 DECIMAL(18,6),
    roe_dt              DECIMAL(18,6),
    roa                 DECIMAL(18,6),
    grossprofit_margin  DECIMAL(18,6),
    netprofit_margin    DECIMAL(18,6),
    debt_to_eqt         DECIMAL(18,6),
    netprofit_yoy       DECIMAL(18,6),
    q_sales_yoy         DECIMAL(18,6),
    or_yoy              DECIMAL(18,6),
    tr_yoy              DECIMAL(18,6),
    q_profit_yoy        DECIMAL(18,6),
    source              VARCHAR(30),
    raw_payload         JSON,
    updated_at          DATETIME       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (symbol, ann_date, end_date, report_type),
    KEY idx_fina_symbol (symbol),
    KEY idx_fina_ann_date (ann_date),
    KEY idx_fina_end_date (end_date)
);
