-- cn_market.SP_BUILD_SECTOR_ROTATION_SIGNAL_LATEST

DROP PROCEDURE IF EXISTS `SP_BUILD_SECTOR_ROTATION_SIGNAL_LATEST`;

CREATE PROCEDURE `SP_BUILD_SECTOR_ROTATION_SIGNAL_LATEST`()
proc: BEGIN
    CALL SP_BUILD_SECTOR_ROTATION_SIGNAL_BY_DATE(NULL);
END proc;
